services:
  unbound:
    image: klutchell/unbound:latest
    container_name: unbound
    hostname: unbound
    pull_policy: always
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - TZ=America/Caracas
    volumes:
      - ./unbound.conf:/etc/unbound/unbound.conf:ro
    healthcheck:
      test: ["CMD", "dig", "-p", "53", "dnssec.works", "@127.0.0.1"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
